# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://wifi-indeauto.nl'
baseurl: ''
title: 'WiFi in de Auto'
description: 'Met WiFi in de auto heb je WiFi waar je ook bent. Voor laptop, tablet of telefoon. Hoe werkt het, wat kost het, en welke abonnementen zijn er?'
permalink: pretty
logo: "/assets/images/mobile-hotspot.png"
locale: "nl_NL"
lang: "nl_NL"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Wat is WiFi in de auto
  url: /
- title: Hoe werkt het
  url: /hoe-werkt-het/
- title: MiFi router kopen
  url: /mifi-router-kopen/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Links
  url: /links/
- title: Over ons
  url: /over/
- title: Terug naar boven
  url: "#top"

# Collections
collections:
  posts:
    title: Blogposts
    output: true
    description: "De laatste ontwikkelingen op het gebied van wifi in de auto"
    feature_text: |
      ## WiFi in de auto blog
    feature_image: "/assets/images/auto-parkeerplaats.jpg"

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

